server:
  port: 8081

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: sales-service
          uri: lb://SALES-SERVICE
          predicates:
            - Path=/sales/**
        - id: app-client
          uri: lb://APP-CLIENT
          predicates:
            - Path=/client/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOSTNAME}:8761/eureka/